# Generated by Django 5.0.1 on 2026-02-08 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngredientSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_title",
                    models.CharField(
                        help_text="Title of this ingredient section (max 150 characters)",
                        max_length=150,
                    ),
                ),
                (
                    "section_order",
                    models.IntegerField(
                        help_text="Order of this section within the recipe (1, 2, 3, ...)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingredient Section",
                "verbose_name_plural": "Ingredient Sections",
                "db_table": "ingredient_sections",
                "ordering": ["recipe", "section_order"],
            },
        ),
        migrations.CreateModel(
            name="InstructionSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_title",
                    models.CharField(
                        help_text="Title of this instruction section (max 150 characters)",
                        max_length=150,
                    ),
                ),
                (
                    "section_order",
                    models.IntegerField(
                        help_text="Order of this section within the recipe (1, 2, 3, ...)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Instruction Section",
                "verbose_name_plural": "Instruction Sections",
                "db_table": "instruction_sections",
                "ordering": ["recipe", "section_order"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipe_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the recipe (must be unique, max 150 characters)",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "recipe_description",
                    models.TextField(
                        help_text="Description of the recipe (max 1000 characters)",
                        max_length=1000,
                    ),
                ),
                (
                    "recipe_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Cloudinary URL for recipe image",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Hors d'oeuvres", "Hors d'oeuvres"),
                            ("Appetizer", "Appetizer"),
                            ("Dinner", "Dinner"),
                            ("Dessert", "Dessert"),
                        ],
                        help_text="Type of course (Breakfast, Lunch, Dinner, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "recipe_type",
                    models.CharField(
                        choices=[
                            ("Entrée", "Entrée"),
                            ("Soup", "Soup"),
                            ("Salad", "Salad"),
                            ("Pizza", "Pizza"),
                            ("Starter", "Starter"),
                            ("Side Dish", "Side Dish"),
                            ("Sauce", "Sauce"),
                        ],
                        help_text="Type of recipe (Entrée, Soup, Salad, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "primary_protein",
                    models.CharField(
                        choices=[
                            ("Beef", "Beef"),
                            ("Chicken", "Chicken"),
                            ("Fish", "Fish"),
                            ("Pork", "Pork"),
                            ("Turkey", "Turkey"),
                            ("Vegetarian / None", "Vegetarian / None"),
                        ],
                        help_text="Primary protein (Beef, Chicken, Fish, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "ethnic_style",
                    models.CharField(
                        choices=[
                            ("American", "American"),
                            ("Chinese", "Chinese"),
                            ("Caribbean", "Caribbean"),
                            ("Indian", "Indian"),
                            ("Italian", "Italian"),
                            ("Korean", "Korean"),
                            ("Mediterranean / Greek", "Mediterranean / Greek"),
                            ("Mexican / Tex-Mex", "Mexican / Tex-Mex"),
                            ("Middle Eastern", "Middle Eastern"),
                            ("Thai", "Thai"),
                        ],
                        help_text="Ethnic cuisine style (Italian, Mexican, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "prep_time",
                    models.IntegerField(
                        help_text="Preparation time in minutes",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cook_time",
                    models.IntegerField(
                        help_text="Cooking time in minutes",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "number_servings",
                    models.IntegerField(
                        help_text="Number of servings this recipe makes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp of recipe creation",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last update"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag - recipe is archived, not permanently deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of deletion", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
                "db_table": "recipes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient_quantity",
                    models.CharField(
                        blank=True,
                        help_text="Quantity (e.g., '2', '1/4', can be null for 'to taste')",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ingredient_uom",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measure (e.g., 'cups', 'tbsp', can be null)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ingredient_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the ingredient (max 150 characters)",
                        max_length=150,
                    ),
                ),
                (
                    "ingredient_order",
                    models.IntegerField(
                        help_text="Order of this ingredient within the section (1, 2, 3, ...)"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Section this ingredient belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.ingredientsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingredient",
                "verbose_name_plural": "Ingredients",
                "db_table": "ingredients",
                "ordering": ["section", "ingredient_order"],
            },
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instruction_step",
                    models.TextField(
                        help_text="The instruction text (max 500 characters)",
                        max_length=500,
                    ),
                ),
                (
                    "step_order",
                    models.IntegerField(
                        help_text="Order of this step within the section (1, 2, 3, ...)"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Section this instruction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructions",
                        to="recipes.instructionsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instruction",
                "verbose_name_plural": "Instructions",
                "db_table": "instructions",
                "ordering": ["section", "step_order"],
            },
        ),
    ]
