# Generated by Django 5.0.1 on 2026-02-08 18:08

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="user",
            field=models.ForeignKey(
                help_text="User who created this recipe",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instructionsection",
            name="recipe",
            field=models.ForeignKey(
                help_text="Recipe this section belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instruction_sections",
                to="recipes.recipe",
            ),
        ),
        migrations.AddField(
            model_name="ingredientsection",
            name="recipe",
            field=models.ForeignKey(
                help_text="Recipe this section belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_sections",
                to="recipes.recipe",
            ),
        ),
        migrations.AddIndex(
            model_name="ingredient",
            index=models.Index(
                fields=["ingredient_name"], name="ingredients_ingredi_99420e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("section", "ingredient_order"), name="unique_ingredient_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="instruction",
            constraint=models.UniqueConstraint(
                fields=("section", "step_order"), name="unique_instruction_order"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["deleted", "-created_at"], name="recipes_deleted_108ed4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["recipe_name"], name="recipes_recipe__fbf73f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("recipe_name"),
                name="unique_recipe_name_case_insensitive",
            ),
        ),
        migrations.AddConstraint(
            model_name="instructionsection",
            constraint=models.UniqueConstraint(
                fields=("recipe", "section_order"),
                name="unique_instruction_section_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientsection",
            constraint=models.UniqueConstraint(
                fields=("recipe", "section_order"),
                name="unique_ingredient_section_order",
            ),
        ),
    ]
