# Generated by Django 6.0.2 on 2026-02-09 21:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_image_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Recipe image (uploaded to Cloudinary)', max_length=255, null=True, verbose_name='image'),
        ),
    ]
