# Generated by Django 6.0.2 on 2026-02-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_remove_recipe_recipe_image_url_recipe_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("Breakfast", "Breakfast"),
                    ("Lunch", "Lunch"),
                    ("Snacks", "Snacks"),
                    ("Appetizer", "Appetizer"),
                    ("Dinner", "Dinner"),
                    ("Breads", "Breads"),
                    ("Dessert", "Dessert"),
                ],
                help_text="Type of course (Breakfast, Lunch, Dinner, etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="primary_protein",
            field=models.CharField(
                choices=[
                    ("Beef", "Beef"),
                    ("Chicken", "Chicken"),
                    ("Fish", "Fish"),
                    ("Pork", "Pork"),
                    ("Turkey", "Turkey"),
                    ("Vegetarian", "Vegetarian"),
                    ("None", "None"),
                ],
                help_text="Primary protein (Beef, Chicken, Fish, etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_type",
            field=models.CharField(
                choices=[
                    ("Entrée (Main)", "Entrée (Main)"),
                    ("Soup", "Soup"),
                    ("Salad", "Salad"),
                    ("Pizza", "Pizza"),
                    ("Pasta", "Pasta"),
                    ("Starter", "Starter"),
                    ("Side Dish", "Side Dish"),
                    ("Sauce", "Sauce"),
                ],
                help_text="Type of recipe (Entrée, Soup, Salad, etc.)",
                max_length=50,
            ),
        ),
    ]
